services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password123"
      POSTGRES_DB: "mydatabase"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./initpg:/docker-entrypoint-initdb.d

volumes:
  pg_data: